version: '3.8'
services:
  app:
    build: .
    ports:
      - "443:443"
      - "8080:8080"
    # 移除 volumes 挂载以避免覆盖容器内的证书，或者确保宿主机根目录有证书
    environment:
      - DB_URL=postgres://docker:floder123@172.17.0.1:5432/gis_db?sslmode=disable
      - REDIS_URL=redis:6379
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: geo-go-redis-1
    restart: always